[server]
maxUploadSize = 500
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#e86132"
backgroundColor = "#f5f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#14263e"
font = "sans serif"
